using System;
using System.Collections.Generic;

namespace Tef.Dominio.Utils
{
    public static class BandeiraPadrao
    {
        private static Dictionary<string, Cartao> Bandeiras = new Dictionary<string, Cartao>();

        static BandeiraPadrao()
        {
            Bandeiras.Add("00001", new Cartao("VISA", "CREDITO"));
            Bandeiras.Add("20002", new Cartao("VISA", "DEBITO"));
            Bandeiras.Add("10002", new Cartao("VISA", "VOUCHER"));
            Bandeiras.Add("00002", new Cartao("MASTER", "CREDITO"));
            Bandeiras.Add("20001", new Cartao("MASTER", "DEBITO"));
            Bandeiras.Add("00012", new Cartao("HIPER", "CREDITO"));
            Bandeiras.Add("20037", new Cartao("HIPER", "DEBITO"));
            Bandeiras.Add("00015", new Cartao("SOROCRED", "CREDITO"));
            Bandeiras.Add("10037", new Cartao("SOROCRED", "VOUCHER"));
            Bandeiras.Add("20003", new Cartao("CABAL", "DEBITO"));
            Bandeiras.Add("10012", new Cartao("CABAL", "VOUCHER"));
            Bandeiras.Add("00030", new Cartao("CABAL", "CREDITO"));
            Bandeiras.Add("10001", new Cartao("TICKET", "VOUCHER"));
            Bandeiras.Add("10024", new Cartao("TICKET", "VOUCHER REFEICAO"));
            Bandeiras.Add("10025", new Cartao("TICKET", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10027", new Cartao("TICKET", "VOUCHER CULTURA"));
            Bandeiras.Add("10054", new Cartao("TICKET COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10003", new Cartao("SODEXO", "CREDITO"));
            Bandeiras.Add("10028", new Cartao("SODEXO", "VOUCHER REFEICAO"));
            Bandeiras.Add("10029", new Cartao("SODEXO", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10030", new Cartao("SODEXO", "GIFT"));
            Bandeiras.Add("10031", new Cartao("SODEXO", "VOUCHER"));
            Bandeiras.Add("10032", new Cartao("SODEXO", "VOUCHER CULTURA"));
            Bandeiras.Add("10033", new Cartao("SODEXO COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10004", new Cartao("NUTRICASH", "VOUCHER"));
            Bandeiras.Add("10053", new Cartao("NUTRICASH", "VOUCHER CULTURA"));
            Bandeiras.Add("10006", new Cartao("PLANVALE", "VOUCHER"));
            Bandeiras.Add("10051", new Cartao("PLANVALE", "VOUCHER CULTURA"));
            Bandeiras.Add("10011", new Cartao("VALECARD", "VOUCHER"));
            Bandeiras.Add("10055", new Cartao("VALECARD", "VOUCHER CULTURA"));
            Bandeiras.Add("10019", new Cartao("ALELO", "VOUCHER"));
            Bandeiras.Add("10021", new Cartao("ALELO", "VOUCHER REFEICAO"));
            Bandeiras.Add("10023", new Cartao("ALELO", "VOUCHER CULTURA"));
            Bandeiras.Add("00031", new Cartao("ELO", "CREDITO"));
            Bandeiras.Add("20032", new Cartao("ELO", "DEBITO"));
            Bandeiras.Add("00041", new Cartao("SICREDI", "CREDITO"));
            Bandeiras.Add("20042", new Cartao("SICREDI", "DEBITO"));
            Bandeiras.Add("00033", new Cartao("POLICARD", "CREDITO"));
            Bandeiras.Add("20034", new Cartao("POLICARD", "DEBITO"));
            Bandeiras.Add("00035", new Cartao("BANESCARD", "CREDITO"));
            Bandeiras.Add("20036", new Cartao("BANESCARD", "DEBITO"));
            Bandeiras.Add("10008", new Cartao("VEROCHEQUE", "VOUCHER"));
            Bandeiras.Add("00043", new Cartao("COOPERCRED", "CREDITO"));
            Bandeiras.Add("10044", new Cartao("COOPERCRED", "VOUCHER"));
            Bandeiras.Add("10056", new Cartao("COOPERCRED", "VOUCHER CULTURA"));
            Bandeiras.Add("10047", new Cartao("VR", "VOUCHER REFEICAO"));
            Bandeiras.Add("10048", new Cartao("VR", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10049", new Cartao("VR COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10050", new Cartao("VR", "VOUCHER CULTURA"));
            Bandeiras.Add("00009", new Cartao("PAO DE ACUCAR", "CREDITO"));
            Bandeiras.Add("10014", new Cartao("DINERS", "VOUCHER"));
            Bandeiras.Add("00038", new Cartao("CETELEM", "CREDITO"));
            Bandeiras.Add("00003", new Cartao("DINERS", "CREDITO"));
            Bandeiras.Add("00004", new Cartao("AMEX", "CREDITO"));
            Bandeiras.Add("00006", new Cartao("SIDECARD", "CREDITO"));
            Bandeiras.Add("00010", new Cartao("FINIVEST", "CREDITO"));
            Bandeiras.Add("00011", new Cartao("JCB", "CREDITO"));
            Bandeiras.Add("10039", new Cartao("VALEMULTI", "VOUCHER"));
            Bandeiras.Add("10040", new Cartao("VALEFROTA", "VOUCHER"));
            Bandeiras.Add("00045", new Cartao("AVISTA", "CREDITO"));
            Bandeiras.Add("00057", new Cartao("MAIS", "CREDITO"));
            Bandeiras.Add("00070", new Cartao("CREDZ", "CREDITO"));
            Bandeiras.Add("00013", new Cartao("AURA", "CREDITO"));
            Bandeiras.Add("10007", new Cartao("BANQUET", "VOUCHER"));
            Bandeiras.Add("10009", new Cartao("SAPORE", "VOUCHER"));
            Bandeiras.Add("10010", new Cartao("BNBCLUBE", "VOUCHER"));
            Bandeiras.Add("10005", new Cartao("GREENCARD", "VOUCHER"));
            Bandeiras.Add("10052", new Cartao("REFEISUL", "VOUCHER CULTURA"));
            Bandeiras.Add("00058", new Cartao("BANPARA", "CREDITO"));
            Bandeiras.Add("20059", new Cartao("BANPARA", "DEBITO"));
            Bandeiras.Add("00060", new Cartao("AMAZONCARD", "CREDITO"));
            Bandeiras.Add("00061", new Cartao("YAMADA", "CREDITO"));
            Bandeiras.Add("00062", new Cartao("GOIASCARD", "CREDITO"));
            Bandeiras.Add("00063", new Cartao("CREDPAR", "CREDITO"));
            Bandeiras.Add("00064", new Cartao("BOTICARIO", "CREDITO"));
            Bandeiras.Add("00065", new Cartao("ASCARD", "CREDITO"));
            Bandeiras.Add("00066", new Cartao("JETPAR", "CREDITO"));
            Bandeiras.Add("00067", new Cartao("MAXXCARD", "CREDITO"));
            Bandeiras.Add("00068", new Cartao("GARANTIDO", "CREDITO"));
            Bandeiras.Add("00069", new Cartao("AMAZONPRIME", "CREDITO"));
            Bandeiras.Add("00014", new Cartao("LOSANGO", "CREDITO"));
            Bandeiras.Add("00008", new Cartao("REDESHOP", "CREDITO"));
            Bandeiras.Add("10070", new Cartao("VR", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10074", new Cartao("PLANVALE COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10072", new Cartao("PLANVALE", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10073", new Cartao("PLANVALE", "VOUCHER REFEICAO"));
            Bandeiras.Add("10075", new Cartao("PLANVALE", "VOUCHER FARMACIA"));
            Bandeiras.Add("10071", new Cartao("PLANVALE", "VOUCHER BENEFICIO"));
            Bandeiras.Add("00090", new Cartao("CALCARD", "CREDITO"));
            Bandeiras.Add("00107", new Cartao("ACCENTIV", "CREDITO"));
            Bandeiras.Add("00108", new Cartao("ASPEB", "CREDITO"));
            Bandeiras.Add("00109", new Cartao("VALE EXPRESS", "CREDITO"));
            Bandeiras.Add("10110", new Cartao("VALE EXPRESS", "VOUCHER"));
            Bandeiras.Add("20111", new Cartao("VALE EXPRESS", "DEBITO"));
            Bandeiras.Add("10112", new Cartao("GOLDICARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10113", new Cartao("FLEETCARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00114", new Cartao("DAYCARD", "CREDITO"));
            Bandeiras.Add("20115", new Cartao("DAYCARD", "DEBITO"));
            Bandeiras.Add("00130", new Cartao("GOODCARD", "CREDITO"));
            Bandeiras.Add("20131", new Cartao("GOODCARD", "DEBITO"));
            Bandeiras.Add("10132", new Cartao("GOODCARD", "VOUCHER"));
            Bandeiras.Add("10133", new Cartao("GOODCARD", "VOUCHER REFEICAO"));
            Bandeiras.Add("10134", new Cartao("GOODCARD", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10135", new Cartao("GOODCARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00131", new Cartao("PAGSIMPLES", "CREDITO"));
            Bandeiras.Add("00132", new Cartao("ICARDS", "CREDITO"));
            Bandeiras.Add("00093", new Cartao("TRICARD", "CREDITO"));
            Bandeiras.Add("00094", new Cartao("TRICARD", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00071", new Cartao("CREDISHOP", "CREDITO"));
            Bandeiras.Add("00072", new Cartao("TICKET", "CREDITO"));
            Bandeiras.Add("00073", new Cartao("LIBERCARD", "CREDITO"));
            Bandeiras.Add("00078", new Cartao("PEELA", "CREDITO"));
            Bandeiras.Add("00084", new Cartao("BANRISUL", "CREDITO"));
            Bandeiras.Add("00086", new Cartao("VERDECARD", "CREDITO"));
            //Bandeiras.Add("00086", new Cartao("VERDECARD", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00087", new Cartao("REFEISUL", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00091", new Cartao("BANESE", "CREDITO"));
            Bandeiras.Add("00095", new Cartao("APOLOCARD", "CREDITO"));
            Bandeiras.Add("00096", new Cartao("GLOBALCOOPER", "CREDITO"));
            Bandeiras.Add("00097", new Cartao("PRATI", "CREDITO"));
            Bandeiras.Add("00098", new Cartao("SUPPERCARD", "CREDITO"));
            Bandeiras.Add("00099", new Cartao("QUALITA", "CREDITO"));
            Bandeiras.Add("00101", new Cartao("TECBIZ", "CREDITO"));
            Bandeiras.Add("00102", new Cartao("TODO", "CREDITO"));
            Bandeiras.Add("00104", new Cartao("VECELLCARD", "CREDITO"));
            Bandeiras.Add("00105", new Cartao("MAXXVAN", "CREDITO"));
            Bandeiras.Add("00118", new Cartao("RVCARDS", "CREDITO"));
            Bandeiras.Add("00119", new Cartao("LEADER", "CREDITO"));
            Bandeiras.Add("00121", new Cartao("TELENET", "CREDITO"));
            Bandeiras.Add("00124", new Cartao("TICKETLOG", "CREDITO"));
            Bandeiras.Add("00127", new Cartao("SOFTNEX", "CREDITO"));
            Bandeiras.Add("10046", new Cartao("VALEFACIL", "VOUCHER"));
            Bandeiras.Add("10076", new Cartao("PEELA", "GIFT"));
            Bandeiras.Add("10077", new Cartao("LIBERCARD", "VOUCHER"));
            //Bandeiras.Add("10082", new Cartao("ALELO COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10082", new Cartao("ELO COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10083", new Cartao("VR", "VOUCHER"));
            Bandeiras.Add("10088", new Cartao("REFEISUL COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10089", new Cartao("REFEISUL", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10090", new Cartao("VEROCHEQUE", "VOUCHER CULTURA"));
            Bandeiras.Add("10100", new Cartao("QUALITA", "GIFT"));
            Bandeiras.Add("10103", new Cartao("TODO", "GIFT"));
            Bandeiras.Add("10116", new Cartao("HUBPREPAID", "VOUCHER"));
            Bandeiras.Add("10117", new Cartao("FLEXFROTA COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10122", new Cartao("TELENET", "VOUCHER"));
            Bandeiras.Add("10123", new Cartao("TELENET COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10125", new Cartao("TICKETLOG COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10129", new Cartao("SOFTNEX", "VOUCHER"));
            Bandeiras.Add("20128", new Cartao("SOFTNEX", "DEBITO"));
            Bandeiras.Add("10136", new Cartao("VELOE COMBUSTIVEL", string.Empty));
            Bandeiras.Add("20071", new Cartao("SOROCRED", "DEBITO"));
            Bandeiras.Add("20072", new Cartao("MAXXICARD", "DEBITO"));
            Bandeiras.Add("20073", new Cartao("MAXXICARD", "CREDITO"));
            Bandeiras.Add("20074", new Cartao("MAXXICARD", "GIFT"));
            Bandeiras.Add("20075", new Cartao("MAXXICARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("20076", new Cartao("TICKET", "DEBITO"));
            Bandeiras.Add("20085", new Cartao("BANRISUL", "DEBITO"));
            Bandeiras.Add("20092", new Cartao("BANESE", "DEBITO"));
            Bandeiras.Add("20106", new Cartao("MAXXVAN", "DEBITO"));
            Bandeiras.Add("20120", new Cartao("CONVENIOFACIL", "CREDITO"));
            Bandeiras.Add("20126", new Cartao("TICKETLOG", "DEBITO"));
            Bandeiras.Add("00137", new Cartao("FORTBRASIL", "CREDITO"));
            Bandeiras.Add("00138", new Cartao("VOXCRED", "CREDITO"));
            Bandeiras.Add("10137", new Cartao("COOPERCRED", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("20132", new Cartao("COOPERCRED", "DEBITO"));
            Bandeiras.Add("10139", new Cartao("WIZEO COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00140", new Cartao("BORBANET", "CREDITO"));
            Bandeiras.Add("10138", new Cartao("COOPERCRED", "VOUCHER REFEICAO"));
            Bandeiras.Add("10140", new Cartao("BEN VISAVALE", "VOUCHER REFEICAO"));
            Bandeiras.Add("10141", new Cartao("BEN VISAVALE", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10022", new Cartao("ALELO", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10142", new Cartao("ABRAPETITE", "VOUCHER"));
            Bandeiras.Add("10143", new Cartao("AVANCARD", "VOUCHER"));
            Bandeiras.Add("00142", new Cartao("BIGCARD", "CREDITO"));
            Bandeiras.Add("10144", new Cartao("BIQ", "VOUCHER"));
            Bandeiras.Add("00143", new Cartao("BONUSCRED", "CREDITO"));
            Bandeiras.Add("10146", new Cartao("BONUSCRED", "VOUCHER"));
            Bandeiras.Add("00144", new Cartao("BRASIL CARD", "CREDITO"));
            //Bandeiras.Add("10146", new Cartao("BRASIL CARD", "VOUCHER"));
            Bandeiras.Add("00145", new Cartao("CONVENIOS CARD", "CREDITO"));
            Bandeiras.Add("10147", new Cartao("CONVENIOS CARD", "VOUCHER"));
            Bandeiras.Add("10149", new Cartao("CREDIALIMENTACAO", "VOUCHER"));
            Bandeiras.Add("00147", new Cartao("DIAMANTE CARD", "CREDITO"));
            Bandeiras.Add("10150", new Cartao("EUCARD", "VOUCHER"));
            Bandeiras.Add("10151", new Cartao("FACECARD", "VOUCHER"));
            Bandeiras.Add("10152", new Cartao("FLEETCARD", "VOUCHER"));
            Bandeiras.Add("00148", new Cartao("FORTCARD", "CREDITO"));
            Bandeiras.Add("00149", new Cartao("JET CARD", "CREDITO"));
            Bandeiras.Add("10153", new Cartao("LECARD", "VOUCHER"));
            Bandeiras.Add("10154", new Cartao("NUTRICARD", "VOUCHER"));
            Bandeiras.Add("00150", new Cartao("ONECARD", "CREDITO"));
            Bandeiras.Add("00151", new Cartao("PERSONALCARD", "CREDITO"));
            Bandeiras.Add("10155", new Cartao("SENFF", "CREDITO"));
            Bandeiras.Add("10156", new Cartao("SINDPLUS", "VOUCHER"));
            Bandeiras.Add("00152", new Cartao("SYSTEM FARMA", "CREDITO"));
            Bandeiras.Add("10157", new Cartao("USECRED", "VOUCHER"));
            Bandeiras.Add("10158", new Cartao("VALESHOP", "VOUCHER"));
            Bandeiras.Add("10159", new Cartao("VEGASCARD", "VOUCHER"));
            Bandeiras.Add("10160", new Cartao("VS CARD", "VOUCHER"));
            Bandeiras.Add("00141", new Cartao("VEGASCARD", "CREDITO"));
            Bandeiras.Add("20133", new Cartao("VEGASCARD", "DEBITO"));
            Bandeiras.Add("00153", new Cartao("LIV", "CREDITO"));
            Bandeiras.Add("20134", new Cartao("LIV", "DEBITO"));
            Bandeiras.Add("10161", new Cartao("ROTACARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("10162", new Cartao("POLICARD", "VOUCHER"));
            Bandeiras.Add("10163", new Cartao("POLICARD COMBUSTIVEL FROTA", string.Empty));
            Bandeiras.Add("10164", new Cartao("POLICARD", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10165", new Cartao("POLICARD", "VOUCHER REFEICAO"));
            Bandeiras.Add("00155", new Cartao("COOPELIFE", "CREDITO"));
            Bandeiras.Add("20136", new Cartao("COOPELIFE", "DEBITO"));
            Bandeiras.Add("10169", new Cartao("SENFF", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10170", new Cartao("SENFF", "VOUCHER REFEICAO"));
            Bandeiras.Add("10171", new Cartao("SENFF", "VOUCHER"));
            Bandeiras.Add("10173", new Cartao("GREENCARD", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10174", new Cartao("GREENCARD", "VOUCHER REFEICAO"));
            Bandeiras.Add("10175", new Cartao("GREENCARD", "VOUCHER CULTURA"));
            Bandeiras.Add("10176", new Cartao("VEROCHEQUE", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10177", new Cartao("VEROCHEQUE", "VOUCHER REFEICAO"));
            Bandeiras.Add("20137", new Cartao("TELENET", "DEBITO"));
            Bandeiras.Add("10172", new Cartao("COOPERCRED", "GIFT"));
            Bandeiras.Add("10168", new Cartao("POLICARD", "GIFT"));
            Bandeiras.Add("10178", new Cartao("POLICARD", "VOUCHER CULTURA"));
            Bandeiras.Add("10179", new Cartao("POLICARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00156", new Cartao("SINDSPAM", "CREDITO"));
            Bandeiras.Add("20138", new Cartao("SINDSPAM", "DEBITO"));
            Bandeiras.Add("00157", new Cartao("PERSONALIDADE CARD", "CREDITO"));
            Bandeiras.Add("00158", new Cartao("RG CARD", "CREDITO"));
            Bandeiras.Add("00159", new Cartao("TAURUS CARD", "CREDITO"));
            Bandeiras.Add("00160", new Cartao("FACILCARD", "CREDITO"));
            Bandeiras.Add("00161", new Cartao("ALGORIX", "CREDITO"));
            Bandeiras.Add("20139", new Cartao("ALGORIX", "DEBITO"));
            Bandeiras.Add("10180", new Cartao("VALESHOP COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00007", new Cartao("PRIVATE LABEL GENERICO", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00164", new Cartao("CARREFOUR", "CREDITO"));
            Bandeiras.Add("00163", new Cartao("ATACADAO", "CREDITO"));
            Bandeiras.Add("00165", new Cartao("PORTALCARD", "CREDITO"));
            Bandeiras.Add("20140", new Cartao("PORTALCARD", "DEBITO"));
            Bandeiras.Add("10181", new Cartao("PORTALCARD COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00166", new Cartao("AVBR", "CREDITO"));
            Bandeiras.Add("00167", new Cartao("VUON", "CREDITO"));
            Bandeiras.Add("00168", new Cartao("CREDCESTA", "CREDITO"));
            Bandeiras.Add("00169", new Cartao("MARKETPAY", "CREDITO"));
            Bandeiras.Add("20141", new Cartao("PERSONALCARD", "DEBITO"));
            Bandeiras.Add("10182", new Cartao("PERSONALCARD", "VOUCHER"));
            Bandeiras.Add("00170", new Cartao("LIFECARD", "CREDITO"));
            Bandeiras.Add("20142", new Cartao("LIFECARD", "DEBITO"));
            Bandeiras.Add("10183", new Cartao("LIFECARD", "VOUCHER"));
            Bandeiras.Add("00171", new Cartao("TRIOCARD", "CREDITO"));
            Bandeiras.Add("20143", new Cartao("TRIOCARD", "DEBITO"));
            Bandeiras.Add("10184", new Cartao("TRIOCARD", "VOUCHER"));
            Bandeiras.Add("00172", new Cartao("ACCREDITO", "CREDITO"));
            Bandeiras.Add("20144", new Cartao("ACCREDITO", "DEBITO"));
            Bandeiras.Add("10185", new Cartao("ACCREDITO", "VOUCHER"));
            Bandeiras.Add("00173", new Cartao("BNBCLUBE", "CREDITO"));
            Bandeiras.Add("20145", new Cartao("BNBCLUBE", "DEBITO"));
            Bandeiras.Add("00174", new Cartao("BRASIL CONVENIOS", "CREDITO"));
            Bandeiras.Add("20146", new Cartao("BRASIL CONVENIOS", "DEBITO"));
            Bandeiras.Add("00175", new Cartao("CDC CARD", "CREDITO"));
            Bandeiras.Add("20147", new Cartao("CDC CARD", "DEBITO"));
            Bandeiras.Add("00176", new Cartao("GRAALCARD", "CREDITO"));
            Bandeiras.Add("20148", new Cartao("GRAALCARD", "DEBITO"));
            Bandeiras.Add("00177", new Cartao("GRANDCARD", "CREDITO"));
            Bandeiras.Add("20149", new Cartao("GRANDCARD", "DEBITO"));
            Bandeiras.Add("00178", new Cartao("ITACARD", "CREDITO"));
            Bandeiras.Add("20150", new Cartao("ITACARD", "DEBITO"));
            Bandeiras.Add("00179", new Cartao("REDEMED", "CREDITO"));
            Bandeiras.Add("00180", new Cartao("SIANET", "CREDITO"));
            Bandeiras.Add("20151", new Cartao("SIANET", "DEBITO"));
            Bandeiras.Add("00181", new Cartao("ECXCARD", "CREDITO"));
            Bandeiras.Add("10186", new Cartao("ECXCARD COMBUSTIVEL FROTA", string.Empty));
            Bandeiras.Add("10187", new Cartao("TRUCKPAG COMBUSTIVEL", string.Empty));
            Bandeiras.Add("00182", new Cartao("DOTZ", "CREDITO"));
            Bandeiras.Add("20152", new Cartao("VERDECARD", "DEBITO"));
            Bandeiras.Add("10188", new Cartao("VISA", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("10189", new Cartao("MASTER", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00183", new Cartao("ACICREDI", "CREDITO"));
            Bandeiras.Add("00184", new Cartao("AESP CONVENIO", "CREDITO"));
            Bandeiras.Add("00185", new Cartao("AGUIA CARD", "CREDITO"));
            Bandeiras.Add("00186", new Cartao("ARCOMCREDICARD", "CREDITO"));
            Bandeiras.Add("00187", new Cartao("ASSUFOP CARD", "CREDITO"));
            Bandeiras.Add("00188", new Cartao("AVANTISYS", "CREDITO"));
            Bandeiras.Add("10190", new Cartao("AZUL CARD", "VOUCHER"));
            Bandeiras.Add("00189", new Cartao("BANDCARD", "CREDITO"));
            Bandeiras.Add("10191", new Cartao("BANDCARD", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10192", new Cartao("BANESE", "VOUCHER REFEICAO"));
            Bandeiras.Add("10193", new Cartao("BANK", "VOUCHER"));
            Bandeiras.Add("10194", new Cartao("BICARTOES", "VOUCHER"));
            Bandeiras.Add("10195", new Cartao("BIGCARD", "VOUCHER"));
            Bandeiras.Add("10196", new Cartao("BLUEBANK", "VOUCHER"));
            Bandeiras.Add("10197", new Cartao("CAMPELOCARD", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("00190", new Cartao("CAMPELOCARD", "CREDITO"));
            Bandeiras.Add("00191", new Cartao("CARTAO CONFIANCA", "CREDITO"));
            Bandeiras.Add("10198", new Cartao("CARTAO CONFIANCA", "VOUCHER"));
            Bandeiras.Add("00192", new Cartao("CARTAO HORTIFRUTI", "CREDITO"));
            Bandeiras.Add("00193", new Cartao("IRANI", "CREDITO"));
            Bandeiras.Add("10199", new Cartao("IRANI", "VOUCHER"));
            Bandeiras.Add("10200", new Cartao("IRANI", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("00194", new Cartao("CARTAO LEVEMAIS", "CREDITO"));
            Bandeiras.Add("00195", new Cartao("CARTAO MONTREAL", "CREDITO"));
            Bandeiras.Add("00196", new Cartao("CARTAO NALIN", "CREDITO"));
            Bandeiras.Add("00197", new Cartao("CARTOES BRAIZINHO", "CREDITO"));
            Bandeiras.Add("00198", new Cartao("CATTANCARD", "CREDITO"));
            Bandeiras.Add("00199", new Cartao("CATTANCARD FORTBRASIL", "CREDITO"));
            Bandeiras.Add("00200", new Cartao("CLUBE DEMAIS", "CREDITO"));
            Bandeiras.Add("10201", new Cartao("CLUBE DEMAIS", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10202", new Cartao("CONDOR", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("00201", new Cartao("COOPECIC CARD", "CREDITO"));
            Bandeiras.Add("00202", new Cartao("COOPERATIVO", "CREDITO"));
            Bandeiras.Add("00203", new Cartao("CREDIALTO CARD", "CREDITO"));
            Bandeiras.Add("00204", new Cartao("CREDINOVA CARD", "CREDITO"));
            Bandeiras.Add("00205", new Cartao("CREDIPINHO CARD", "CREDITO"));
            Bandeiras.Add("10203", new Cartao("EDIZ", "VOUCHER"));
            Bandeiras.Add("10204", new Cartao("ENSCON CARD", "VOUCHER"));
            Bandeiras.Add("00206", new Cartao("FINANCIAL CARTOES", "CREDITO"));
            Bandeiras.Add("10205", new Cartao("FORMOSA", "VOUCHER"));
            Bandeiras.Add("10206", new Cartao("GIRACARD", "VOUCHER"));
            Bandeiras.Add("10207", new Cartao("IDEAL SUPERMERCADOS", "VOUCHER"));
            Bandeiras.Add("00207", new Cartao("IMPERATRIZ", "CREDITO"));
            Bandeiras.Add("10208", new Cartao("IMPERATRIZ", "VOUCHER"));
            Bandeiras.Add("00208", new Cartao("LAGOACRED CARD", "CREDITO"));
            Bandeiras.Add("00209", new Cartao("MAISFACIL", "CREDITO"));
            Bandeiras.Add("00210", new Cartao("NEOCARD", "CREDITO"));
            Bandeiras.Add("10209", new Cartao("NEUS", "VOUCHER"));
            Bandeiras.Add("10210", new Cartao("NEUS MINAS", "VOUCHER"));
            Bandeiras.Add("10211", new Cartao("PAGUEMENOS", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10212", new Cartao("PG CARD", "VOUCHER"));
            Bandeiras.Add("00211", new Cartao("PITCARD", "CREDITO"));
            Bandeiras.Add("00212", new Cartao("QUEIROZ PREMIUM", "CREDITO"));
            Bandeiras.Add("10213", new Cartao("QUEIROZ PREMIUM", "VOUCHER"));
            Bandeiras.Add("10214", new Cartao("QUEIROZ PREMIUM", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("00213", new Cartao("REDE CUIDAR", "CREDITO"));
            Bandeiras.Add("00214", new Cartao("SAVEGNAGO", "CREDITO"));
            Bandeiras.Add("00215", new Cartao("SERTAO CARD", "CREDITO"));
            Bandeiras.Add("00216", new Cartao("SERVIR", "CREDITO"));
            Bandeiras.Add("00217", new Cartao("SIACARD", "CREDITO"));
            Bandeiras.Add("00218", new Cartao("SIM", "CREDITO"));
            Bandeiras.Add("10215", new Cartao("SINDCONVENIOS", "VOUCHER"));
            Bandeiras.Add("00219", new Cartao("SITECC", "CREDITO"));
            Bandeiras.Add("00220", new Cartao("SOLLUS", "CREDITO"));
            Bandeiras.Add("10216", new Cartao("SOLLUS", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10217", new Cartao("SOLLUS", "VOUCHER REFEICAO"));
            Bandeiras.Add("00221", new Cartao("STILOA CARD", "CREDITO"));
            Bandeiras.Add("00222", new Cartao("SUPERCRED", "CREDITO"));
            Bandeiras.Add("00223", new Cartao("TIPCARD", "CREDITO"));
            Bandeiras.Add("00224", new Cartao("TORRA TORRA", "CREDITO"));
            Bandeiras.Add("00225", new Cartao("UAICARD", "CREDITO"));
            Bandeiras.Add("10218", new Cartao("SUPERCRED", "VOUCHER"));
            Bandeiras.Add("10219", new Cartao("VALEMAIS", "VOUCHER"));
            Bandeiras.Add("10220", new Cartao("VALEMAIS", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10221", new Cartao("VALLE REAL", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10222", new Cartao("VEGAS", "VOUCHER"));
            Bandeiras.Add("00226", new Cartao("VIPCARD", "CREDITO"));
            Bandeiras.Add("00227", new Cartao("ZEMA", "CREDITO"));
            Bandeiras.Add("10223", new Cartao("PAGUEMENOS", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10224", new Cartao("PARACATU CARD", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10225", new Cartao("SERVIR", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10226", new Cartao("SERTAO CARD", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10227", new Cartao("SINTRAM", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10228", new Cartao("VALEMAIS", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10229", new Cartao("VALLE REAL", "VOUCHER BENEFICIO"));
            Bandeiras.Add("10230", new Cartao("SFORZA", "VOUCHER ALIMENTACAO"));
            Bandeiras.Add("10231", new Cartao("SFORZA", "VOUCHER REFEICAO"));
            Bandeiras.Add("00228", new Cartao("SISCRED", "CREDITO"));
            Bandeiras.Add("10237", new Cartao("VALECARD", "VOUCHER ALIMENTAÇÃO"));
            Bandeiras.Add("10238", new Cartao("VALECARD", "VOUCHER REFEIÇÃO"));
            Bandeiras.Add("00231", new Cartao("BRADESCARD", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00232", new Cartao("BRADESCARD ELO", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00233", new Cartao("BRADESCARD VISA", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("00234", new Cartao("BRADESCARD MASTERCARD", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("10239", new Cartao("VALEPRES SYSDATA", "GIFT"));
            Bandeiras.Add("10240", new Cartao("VALEPRES PEELA", "GIFT"));
            Bandeiras.Add("00235", new Cartao("GOLDENFARMA", "CREDITO"));
            Bandeiras.Add("00237", new Cartao("MAISFACIL", "CREDITO PRIVATE LABEL"));
            Bandeiras.Add("10252", new Cartao("BLACKHAWK GIFT", "GIFT"));
            Bandeiras.Add("20155", new Cartao("BLACKHAWK PRÉ-PAGO", "DEBITO PRIVATE LABEL"));
            Bandeiras.Add("600012", new Cartao("PIC PAY", "CARTEIRA DIGITAL"));
            Bandeiras.Add("260005", new Cartao("VEE", "CARTEIRA DIGITAL"));
            Bandeiras.Add("290006", new Cartao("MERCADO PAGO", "CARTEIRA DIGITAL"));
            Bandeiras.Add("380009", new Cartao("ITI ITAU", "CARTEIRA DIGITAL"));
            Bandeiras.Add("60110024", new Cartao("PIX", "CARTEIRA DIGITAL"));
        }

        public static string ObterCartao(string chave)
        {
            var card = GetCard(chave);
            return string.IsNullOrEmpty(card.Nome) ? string.Empty 
                                                   : $"{card.Nome}|{card.Tipo}|{chave}";
        }

        public static string ObterBandeira(string chave)
        {
            return GetCard(chave).Nome;
        }

        public static string ObterTipoCartao(string chave)
        {
            return GetCard(chave).Tipo;
        }

        private static Cartao GetCard(string chave)
        {
            Bandeiras.TryGetValue(chave, out var cartao);
            return cartao;
        }

        class Cartao
        {
            public Cartao(string nome, string tipo)
            {
                Nome = nome;
                Tipo = tipo;
            }

            public string Nome { get; set; }
            public string Tipo { get; set; }
        }
    }
}
